package com.example.ChatApp;

import com.example.ChatApp.Models.Users;
import com.example.ChatApp.Repositories.UsersRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.mongodb.repository.config.EnableMongoRepositories;
import org.springframework.security.crypto.bcrypt.BCrypt;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableMongoRepositories
public class ChatAppApplication implements CommandLineRunner {
	@Autowired
	private UsersRepository usersRepository;
	public static void main(String[] args) {
		SpringApplication.run(ChatAppApplication.class, args);
	}
	public void run(String... args){
		Users users=new Users();
		users.setEmail("user1@gmail.com");
		users.setDisplay_name("user1");
		users.setPassword(new BCryptPasswordEncoder().encode("user1"));
		usersRepository.save(users);
	}
}
